language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get -u github.com/kardianos/govendor && govendor sync
  - go get -u github.com/alecthomas/gometalinter && gometalinter --install
  - go get -u github.com/bradleyfalzon/revgrep/...

script:
  - gometalinter --vendor ./... 2>&1 | revgrep origin/master
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

notifications:
  email: false
