language: go

go:
  - "1.7.x"
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get -u github.com/kardianos/govendor && govendor sync
  - go get -u github.com/alecthomas/gometalinter && gometalinter --install

script:
  - gometalinter --vendor ./... || true
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
