language: go

go:
  - 1.8.x
  - tip

before_install:
  - go get -u github.com/kardianos/govendor
  - govendor sync

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
