language: go

go:
  - 1.8.x
  - tip

before_install:
  - go get -u github.com/kardianos/govendor
  - govendor sync

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /vendor/)

after_success:
  - bash <(curl -s https://codecov.io/bash)
